### ISSUE TITLE
Adding an option to compile a cell/the whole kernel to c/cpp?

### ISSUE THREAD

**Issue by unexploredtest** [stisa/jupyternim#25]
First off, I want to thank you for making such an amazing too, many thanks :)
So, I don't think currently there is such a feature. Some libraries require Nim to be compiled in C/C++, because they depend on some C/C++ code. Having an option, possibly a magic command if possible or basically compiling the whole kernel to cpp/c is useful.
I did some digging and it seems like it is possible to set compilation to cpp in `src/jupyternimpkg/sockets.nim`, with basically changing `nim c` to `nim cpp` and it worked. I think it is possible to make such an option so that somebody can choose between different types compilations.

**Comment by stisa** [comment]
You should be able to just pass the backend via the existing flag mechanism, does that not work for you?
eg: `#>--backend:cpp` at the top of a block.
The kernel itself is compiled to C by nimble install, but you can clone the repo and compile manually to cpp if you really want it, although I don't really see the point to that.

**Comment by unexploredtest** [comment]
> You should be able to just pass the backend via the existing flag mechanism, does that not work for you?
eg: #>--backend:cpp at the top of a block.

No, it's not working

**Comment by stisa** [comment]
OK, looks like I forgot my own way of defining flags, sorry.
It works for me by pasting `#>flags --backend:cpp` at the top of a code cell.  
Note that this will change the compilation of all the notebook to cpp, and due to the way this is done in the background, it will affect previous blocks too, so you can't have a block compiled to c and another with cpp (yet?).

The default is already compiling to C, it basically writes out a temporary nim file, compiles it, and show you only the output from the latest block.  
I have a super experimental mode with hot code reloading support, but it had some pretty serious bugs like crashing when echoing a float number due to bugs in the compiler so that is on hold for now, I will revisit it at some point (probably when incremental compilation gets more stable).

ps: Thanks for using this! I'm always happy to get feedback and bug reports

**Comment by unexploredtest** [comment]
> It works for me by pasting #>flags --backend:cpp at the top of a code cell.

Thanks, that worked! Closing the issue now...

> I have a super experimental mode with hot code reloading support, but it had some pretty serious bugs like crashing when echoing a float number due to bugs in the compiler so that is on hold for now, I will revisit it at some point (probably when incremental compilation gets more stable).

Intersting, looking forward to it :)

> ps: Thanks for using this! I'm always happy to get feedback and bug reports

Thank you! I was so happy when I found out you could use Jupyter Notebook with Nim, as I'm kinda new to it and I've came from a Python background.
