### ISSUE TITLE
INim => JNim ? inim already taken by https://github.com/AndreiRegiani/INim

### ISSUE THREAD

**Issue by timotheecour** [stisa/jupyternim#5]
and JNim would be more logical with "A Jupyter kernel for nim"
(would cause conflict with `nimble install inim`)

**Comment by stisa** [comment]
The name INim is in line with most other IPython kernels (see eg. [here](https://github.com/jupyter/jupyter/wiki/Jupyter-kernels)).   

I understand the conflict with inim, and since I never registered the package on nimble (even though this repo is from 2016) I will have to change it once I decide it's ready to be published, but I'll probably have to choose something like `jupyternim` or `inimkernel`.    

(by the way, `jnim` is already taken by https://github.com/yglukhov/jnim )

**Comment by ruivieira** [comment]
I vote for `jupyternim`.

Although there's no standard (https://github.com/jupyter/jupyter/wiki/Jupyter-kernels) and `Kernel` seems to be more common, having `jupyter` on the project name makes it clearer IMO.

**Comment by timotheecour** [comment]
agreed on `jupyternim`

**Comment by CodeDoes** [comment]
nimju

**Comment by stisa** [comment]
Name changed to `jupyternim`
