### ISSUE TITLE
Error installing jupyternim from source on macOS

### ISSUE THREAD

**Issue by ruivieira** [stisa/jupyternim#6]
`nim -v`:
```
Nim Compiler Version 0.18.0 [MacOSX: amd64]
Copyright (c) 2006-2018 by Andreas Rumpf

active boot switches: -d:release -d:useLinenoise
```
`nimble -v`:
```
nimble v0.8.10 compiled at 2018-03-11 16:16:29
git hash: couldn't determine git hash
```
OS: macOS High Sierra (10.13.6 (17G65))

_What did I do?_

1. Cloned this repo (worked)
2. ran `nimble build` (worked)
3. ran `jupyternim` (did not work)

_What happened?_

Error message:
```
Installing Jupyter Nim Kernel
jupyternim.nim(51)       jupyternim
sysio.nim(409)           writeFile
system.nim(2839)         sysFatal
Error: unhandled exception: cannot open:    Warning: Package 'jupyternim' has an incorrect structure. It should contain a single directory hierarchy for source files, named 'jupyternimpkg', but file 'sockets.nim' is in a directory named 'jupyternim' instead. This will be an error in the future.
      Hint: If 'jupyternim' contains source files for building 'jupyternim', rename it to 'jupyternimpkg'. Otherwise, prevent its installation by adding `skipDirs = @["jupyternim"]` to the .nimble file.
     Error: At least one of the specified packages was not found/jupyternimspec/kernel.json [IOError]
```

_What did expect to happen?_

The `nim` kernel to be installed.

**Comment by cloud-oak** [comment]
I'm getting a similar Error on Ubuntu 18.04 with nim 0.19.0 and nimble v0.9.0.
No matter what I do, in the end it comes down to this
`Error: At least one of the specified packages was not found/jupyternimspec/kernel.json [IOError]`

**Comment by stisa** [comment]
Thanks for the reports!  
I think this is due to [how nimble works](https://github.com/nim-lang/nimble#hybrids) (see also [here](https://github.com/nim-lang/nimble/issues/308)) as it refuses to install the package, and the call to find the package directory then fails.  
I'd really prefer not to change to `jupyternimpkg`, but it's probably the easiest solution, aside from combining all files and deleting the `jupyternim` folder entirely.   
I'll try looking for other solutions (possibly fixing nimble if it's easy enough).
It's probably a good idea to also add some checks for the output of `nimble path jupyternim`,
